from EXTENSIONS.EXT_NITROGEN_EASTER_EGG import *
from EXTENSIONS.EXT_EASY_TAB_CHANGING import *
from EXTENSIONS.EXT_NITRO_SYNTAX import *
def EXECUTE_EXTENSION():
  EXT_NITROGEN_EASTER_EGG()
  EXT_EASY_TAB_CHANGING()
  EXT_NITRO_SYNTAX()
